[build]
    command = "npm run build" # how to trigger a build
    publish = "./static/frontend" # what folder to publish 

[[redirects]]
    from = "/*" 
    to = "/templates/frontend/index.html" # to this html page
    status = 200 # with this status
