[build]
    command = "npm run build" # how to trigger a build
    publish = "./static/frontend" # what folder to publish 

[[redirects]]
    from = "/*" 
    to = "/templates/frontend/index.html" # to this html page
    status = 200 # with this status

[[redirects]]
    from = "/login"
    to = "../Users/templates/users/login.html"
    status = 200

[[redirects]]
    from = "/logout"
    to = "../Users/templates/users/logout.html"
    status = 200

[[redirects]]
    from = "/signup"
    to = "../Users/templates/users/signup.html"
    status = 200
