# Generated by Django 4.0.4 on 2022-05-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_friends_mainuser_alter_post_mainuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, default='This is the description'),
        ),
    ]
