# Generated by Django 4.0.4 on 2022-05-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_friends_mainuser_alter_post_mainuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='_audio',
        ),
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.BinaryField(blank=True, db_column='audio'),
        ),
    ]
