# Generated by Django 4.0.4 on 2022-05-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_friends_mainuser_alter_post_mainuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='discription',
            field=models.TextField(default='Lets Introduce Yourself!'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ProfileImg',
            field=models.CharField(default='https://www.clipartmax.com/png/middle/318-3182943_admin-blank-user-profile.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='displayName',
            field=models.CharField(default='User', max_length=50, unique=True),
        ),
    ]
