# Generated by Django 4.0.4 on 2022-05-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_discription_alter_userprofile_profileimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='discription',
            field=models.TextField(default='Lets Introduce Yourself!', null=True),
        ),
    ]
