# Generated by Django 4.0.4 on 2022-05-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='discription',
            field=models.TextField(db_column='discription', default='Lets Introduce Yourself!', null=True),
        ),
    ]
