# Generated by Django 4.0.4 on 2022-05-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_friends_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='test',
        ),
    ]
