# Generated by Django 4.0.4 on 2022-05-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_friends_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='mainUser',
            new_name='main_user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='mainUser',
            new_name='main_user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='mainUser',
            new_name='main_user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='ProfileImg',
            new_name='profile_img',
        ),
    ]
