# Generated by Django 4.0.4 on 2022-05-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_mainuser_friends_main_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='displayName',
            new_name='display_name',
        ),
    ]
