# Generated by Django 4.0.4 on 2022-05-10 12:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_displayname_userprofile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='_audio',
            field=models.BinaryField(blank=True, db_column='audio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
