# Generated by Django 4.0.4 on 2022-05-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_userprofile_description'),
        ('api', '0011_rename_displayname_userprofile_display_name'),
    ]

    operations = [
    ]
