# Generated by Django 4.0.4 on 2022-05-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_post__audio_alter_userprofile_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_audio',
            new_name='audio',
        ),
    ]
