# Generated by Django 4.0.4 on 2022-05-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_userprofile_profile_img'),
        ('api', '0015_alter_post_audio'),
    ]

    operations = [
    ]
