# Generated by Django 4.0.4 on 2022-05-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_friends_followers_alter_friends_following_and_more'),
        ('api', '0016_merge_20220510_2310'),
    ]

    operations = [
    ]
