# Generated by Django 4.0.4 on 2022-05-12 09:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20220512_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='followers',
            field=models.TextField(blank=True, db_column='followers'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='following',
            field=models.TextField(blank=True, db_column='following'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='friends',
            field=models.TextField(blank=True, db_column='friends'),
        ),
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.FileField(upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, default='https://www.clipartmax.com/png/middle/318-3182943_admin-blank-user-profile.png', null=True, upload_to=api.models.upload_to),
        ),
    ]
