# Generated by Django 4.0.4 on 2022-05-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20220512_0918'),
        ('api', '0018_alter_friends_followers_alter_friends_following_and_more'),
    ]

    operations = [
    ]
