# Generated by Django 4.0.4 on 2022-05-12 11:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20220512_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, default='http://127.0.0.1:8000/media/images/default.jpg', null=True, upload_to=api.models.upload_to),
        ),
    ]
